### ISSUE TITLE
PMI Support

### ISSUE THREAD

**Issue by jdinan** [regrant/sandia-shmem#23]
Current PMI support is a mess; it relies on being able to pull PMI headers/library from the Portals 4 code.  Find a way to make this better.  Could be adding a launcher to Sandia SHMEM that can be selected at compile time, or modifying the build to use PMI from the system MPI library.

**Comment by kseager** [comment]
We've already tackled this issue and have a variety of solutions: from enabling configuration to accept a *.so that has PMI symbols to our own PMI embedded into the code base that just needs a PMI compliant launcher.

**Comment by kseager** [comment]
adding to this: refactor SHMEM-PMI to "--enable-pmi-simple"
